version: "3.8"
services:
  db:
    container_name: identity_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: identity_service

    ports:
      - "5432:5432"

    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 200m

    networks:
      - network_shared

networks:
  network_shared:
    external: true