version: '3.8'

services:
    identity_service:
        build:
            context: .              # This specifies the build context (current directory)
            dockerfile: Dockerfile-jlink   # Path to the Dockerfile (relative to context)
        container_name: app_identity_service
        image: app_identity_service:latest
        environment:
            SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
            SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
            SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
            SPRING_JWT_SIGNERKEY: ${SPRING_JWT_SIGNERKEY}

            CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
            CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
            CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}

            SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
            SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
            SPRING_REDIS_USERNAME: ${SPRING_REDIS_USERNAME}
            SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
            SPRING_REDIS_SSL: ${SPRING_REDIS_SSL}

        ports:
            - "9000:9000"
        restart: unless-stopped    # Restart policy in case the container stops unexpectedly
        deploy:
            resources:
                limits:
                    cpus: '0.3' # it means using limit 30% cpu
                    memory: 300m # it means using limit 30% ram
        networks:
            - network_shared
networks:
    network_shared:
        external: true
