spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
  cloudinary:
    cloud-name: ${CLOUDINARY_CLOUD_NAME}
    api-key: ${CLOUDINARY_API_KEY}
    api-secret: ${CLOUDINARY_API_SECRET}
  redis:
    host: ${SPRING_REDIS_HOST}
    port: ${SPRING_REDIS_PORT}
    username: ${SPRING_REDIS_USERNAME}
    password: ${SPRING_REDIS_PASSWORD}
    ssl: ${SPRING_REDIS_SSL}
    timeout: 5000

    springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      path: /swagger-ui.html
      operations-sorter: alpha
      tags-sorter: alpha
  devtools:
    restart:
      enabled: false
  server:
    port: ${PORT:9000}
  application:
    name: TuanHuy
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/identity_service}
    # có thể viết tất cả các thông tin trên 1 url recommend là ko
    # jdbc:postgresql://<HOST>:<PORT>/<name_DB_in_server>?sslmode=require
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:12345}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5  # Giảm từ 10 xuống 5
      minimum-idle: 2       # Giảm từ 5 xuống 2
      idle-timeout: 10000   # Giảm từ 30000 xuống 10000 (10 giây)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  thymeleaf:
    enabled: true
    cache: true
    prefix: "classpath:/templates/"
    suffix: ".html"
  logging:
    level:
      root: INFO
      org.springframework.security: DEBUG # display errors detail about spring security
      org.hibernate: DEBUG # display errors detail about query sql
  jwt:
    signerKey: ${SPRING_JWT_SIGNERKEY}
api:
  base-url: ${API_BASE_URL:http://localhost:8080/api/v1/download}
app:
  upload:
    dir: "E:/personal_project"