spring:
  application:
    name: TuanHuy
  datasource:
    url: jdbc:postgresql://localhost:5432/identity_service
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  jwt:
    signerKey: "ZQM5hQ9xYRxNzMA/PsJggsQllKFiOz6mDyd372mZ52OwLlj/MbpzB6DTtCp4aWuv"